version: "3"
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=docker_test_app_1_development
      - MYSQL_ROOT_HOST=%
    logging:
      driver: "none"
  web:
    build: .
    #image: shivakumaarmgs/ruby2.1.2-test:v3
    command: bundle exec rspec spec/features
    #command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3001:3000"
      - "3011:3010"
    environment:
      - TEST_APP_PORT=3011
      - SELENIUM_PORT=4444
    entrypoint:
      - bin/entry
    depends_on:
      - db
      - selenium
  selenium:
    image: selenium/standalone-chrome
    logging:
      driver: "none"
