version: "3"
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=docker_test_app_1_development
      - MYSQL_ROOT_HOST=%
    logging:
      driver: "none"
  web:
    image: shivakumaarmgs/ruby2.1.2-test:v4
    command: /myapp/test.sh
    environment:
      - TEST_APP_PORT=3010
      - SELENIUM_PORT=4444
    entrypoint:
      - /myapp/entry.sh
    depends_on:
      - db
      - selenium
  selenium:
    image: selenium/standalone-chrome
    logging:
      driver: "none"
